<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace format_aicourse\output\report;

use context_course;
use core\output\named_templatable;
use core_component;
use format_aicourse\local\contentindex;
use renderable;
use renderer_base;
use stdClass;

/**
 * The "Course Content" tab of the per-course AI Tutor report.
 *
 * Shows what the AI tutor has indexed for this course: a count of sections, activities and
 * indexed characters, the course summary, and one card per activity.
 *
 * @package    format_aicourse
 * @copyright  2026 LMS-Labs
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class contenttab implements named_templatable, renderable {
    /** @var int Number of characters of an activity shown in the card preview. */
    public const PREVIEW_LENGTH = 150;

    /** @var stdClass Course record. */
    protected $course;

    /** @var context_course Course context. */
    protected $context;

    /**
     * Constructor.
     *
     * @param stdClass $course Course record.
     * @param context_course $context Course context.
     */
    public function __construct(stdClass $course, context_course $context) {
        $this->course = $course;
        $this->context = $context;
    }

    /**
     * Get the name of the template to use for this templatable.
     *
     * @param renderer_base $renderer The renderer requesting the template name.
     * @return string
     */
    public function get_template_name(renderer_base $renderer): string {
        return 'format_aicourse/report_content_tab';
    }

    /**
     * Export the data for the mustache template.
     *
     * Pre-escaped values in the returned context, all rendered with a triple mustache:
     *  - coursesummary: already through format_string() (in contentindex) and format_text().
     *  - activities[].name: already through format_string() (in contentindex).
     *  - activities[].icon: markup generated by core's own pix_icon output component.
     * Everything else is plain text and is rendered with a double mustache.
     *
     * @param renderer_base $output Typically, the renderer that is calling this function.
     * @return stdClass Data context for format_aicourse/report_content_tab.
     */
    public function export_for_template(renderer_base $output): stdClass {
        // ACF-FIX-2.0: contentindex::get_course_content_for_ai() runs 80-200 DB queries and parses
        // attached PDFs. It used to run unconditionally at the top of the page, including on the
        // chat history tab which never touches the result. It is now built only by this tab.
        $content = contentindex::get_course_content_for_ai($this->course);

        $totalchars = strlen((string) $content['course_summary']);
        $activities = [];
        foreach ($content['activities'] as $activity) {
            $body = (string) $activity['content'];
            $totalchars += strlen($body);
            $preview = trim(strip_tags($body));
            $activities[] = (object) [
                'name' => (string) $activity['name'],
                'type' => (string) $activity['type'],
                'icon' => $this->get_activity_icon($output, (string) $activity['type']),
                'haspreview' => ($preview !== ''),
                'preview' => shorten_text($preview, self::PREVIEW_LENGTH),
            ];
        }

        $summary = (string) $content['course_summary'];
        $hassummary = (trim($summary) !== '');

        return (object) [
            'sectioncount' => count($content['sections']),
            'activitycount' => count($content['activities']),
            'charactercount' => number_format($totalchars),
            'hascoursesummary' => $hassummary,
            'coursesummary' => $hassummary
                ? format_text($summary, FORMAT_HTML, ['context' => $this->context])
                : '',
            'activities' => $activities,
            'hasactivities' => !empty($activities),
        ];
    }

    /**
     * The icon for an activity type, using the module's own Moodle icon.
     *
     * ACF-FIX-2.1: this replaces a hand-maintained table of eleven inline SVGs that silently fell
     * back to a plain circle for every module it did not know about. The module monologo is
     * checked on disk first, so an unknown or uninstalled module name can never produce a request
     * for a missing image (which would be a console error on the report page).
     *
     * @param renderer_base $output The renderer, used to build the icon markup.
     * @param string $modname Module name, e.g. 'quiz'.
     * @return string Icon markup generated by core's pix_icon output component.
     */
    protected function get_activity_icon(renderer_base $output, string $modname): string {
        $component = 'mod_' . clean_param($modname, PARAM_PLUGIN);
        $directory = core_component::get_component_directory($component);
        if ($directory !== null) {
            foreach (['svg', 'png', 'gif'] as $extension) {
                if (file_exists($directory . '/pix/monologo.' . $extension)) {
                    return $output->pix_icon('monologo', '', $component, ['class' => 'icon']);
                }
            }
        }
        return $output->pix_icon('i/course', '', 'moodle', ['class' => 'icon']);
    }
}
